apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: edu-stoic-dubinsky
  labels:
    app: django-app
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "список доступных хостов (пример 127.0.0.1, 192.168.59.1, your-site.online)"
