apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app: django
data:
  SECRET_KEY: "c0e)1&48x%msmbg!uqlh-055!i50l3bj9_7$wxc&adp=7odk4s"
  DEBUG: "False"
  ALLOWED_HOSTS: "edu-stoic-dubinsky.sirius-k8s.dvmn.org"