apiVersion: v1
kind: Service
metadata:
  name: django-app
  namespace: edu-stoic-dubinsky
  labels:
    app.kubernetes.io/name: django-deployment
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30261
  type: NodePort