apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-label
  name: nginx
  namespace: edu-stoic-dubinsky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-label
  template:
    metadata:
      labels:
        app: nginx-label
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx-app
        ports:
        - containerPort: 80
          protocol: TCP