apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: edu-stoic-dubinsky
  labels:
    app: nginx-label
spec:
  selector:
    app: nginx-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30261
  type: NodePort