apiVersion: v1
kind: Pod
metadata:
  name: test-ubuntu-pod
  namespace: edu-stoic-dubinsky
spec:
  containers:
  - name: test-container
    image: ubuntu:latest
    command: [ "/bin/sh", "-c" ]
    args:
      - |
        apt-get update && apt-get install -y postgresql-client
        psql -h $PGHOST -U $PGUSER -d $PGDATABASE -p $PGPORT -c "SELECT version();"
        while true; do sleep 86400; done
    env:
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres
            key: password
      - name: PGHOST
        valueFrom:
          secretKeyRef:
            name: postgres
            key: host
      - name: PGUSER
        valueFrom:
          secretKeyRef:
            name: postgres
            key: username
      - name: PGDATABASE
        valueFrom:
          secretKeyRef:
            name: postgres
            key: name
      - name: PGPORT
        valueFrom:
          secretKeyRef:
            name: postgres
            key: port
    volumeMounts:
    - name: ssl-certs
      mountPath: "/.postgresql"
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: ssl-certs
    secret:
      secretName: postgres-ssl-secret
      items:
      - key: ssl-certs
        path: root.crt
