apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  labels:
    app: django
data:
  SECRET_KEY: "your-secret-key в формате base64"
  DATABASE_URL: "postgres://<пользователь>:<пароль>@<хост>:<порт>/<имя_базы_данных в формате base64>"