apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app: django
data:
  SECRET_KEY: "your-secret-key"
  DATABASE_URL: "postgres://<пользователь>:<пароль>@<хост>:<порт>/<имя_базы_данных>"
  DEBUG: "False"
  ALLOWED_HOSTS: "список доступных хостов (пример 127.0.0.1, 192.168.59.1, your-site.online)"
